---
title: "Lending Club dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

Dashboard
=====================================
```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyr)
library(plotly)
library(scales)
library(heatmaply)
library(highcharter)
library(treemap)
 
## We will used filtered data for a few years due to size limitation on publishing it
# load("./Data/accepted_loan_subset_data.RData")
# accepted_loan_df <- accepted_loan_subset_df %>%
#   filter(year == "2011" | year == "2012" | year == "2013" | year == "2014")
# rm(accepted_loan_subset_df)

accepted_loan_df <- readRDS("accepted_loans_2011_to_2014.Rds")
int_rates_2017 <- readRDS("accepted_loans_int_rate_2017.Rds")
```

Row {data-width=500}
-----------------------------------------------------------------------

### 36-Month Loans

```{r}
## Calc Last Quarter Interest Rate avg by Term 
qtrly_int_rates <- int_rates_2017 %>% 
#  filter(year == "2017", month == "Jul" | month == "Aug" | month == "Sep") %>% 
  group_by(term) %>% 
  summarise(LastQtrAvgIntRate = mean(InterestRate/100)) 
valueBox(percent(qtrly_int_rates$LastQtrAvgIntRate[1]), color = "primary",
         caption = "36-Month Loans (Last Qarter Avg Interest Rate)", icon="fa-thumbs-up")
```

### 60-Month Loans

```{r}
valueBox(percent(qtrly_int_rates$LastQtrAvgIntRate[2]), color = "info",
         caption = "60-Month Loans (Last Qarter Avg Interest Rate)", icon="fa-thumbs-up")
```

### Total Issued Loan

```{r}
valueBox(dollar_format()(sum(as.numeric(accepted_loan_df$loan_amnt), na.rm = T)), color = "orange",
         caption = "Total Issued Loan Amount from 2011 to 2014", icon="ion-speedometer")
```


Row
-----------------------------------------------------------------------

### Loan Category Share

```{r}
dt1 <- accepted_loan_df %>% 
  group_by(loan_status) %>% 
  summarise(LoanAmount = sum(as.numeric(loan_amnt),na.rm = T), 
            NumberofLoans = n()) %>% 
  as.data.frame()
# dt1$loan_status[1] <- NA
# dt1 <- dt1[complete.cases(dt1),]
knitr::kable(dt1)
```

### Loan Status Distribution

```{r}
plot_ly(dt1, labels = ~loan_status, values = ~LoanAmount, type = 'pie') %>%
  layout(title = 'Loan Status by Count and Outstanding',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```


### Grade vs Interest

```{r}
plot_ly(accepted_loan_df, x=~grade, y=~int_rate, color = ~Risk_Score, type = "box")
```


Row {data-width=500}
-----------------------------------------------------------------------

### TotalLoan All Years

```{r}
dt2 <- accepted_loan_df %>% 
  group_by(year) %>% 
  summarise(TotalLoan = sum(as.numeric(loan_amnt),na.rm = T), 
            NumberofLoans = n()) %>% 
  as.data.frame()
# dt2$year[1] <- NA
# dt2 <- dt2[complete.cases(dt2),]
yr <- levels(factor(dt2$year))
plot_ly(dt2,x=~year, 
        y=~TotalLoan, 
        text = dollar_format()(dt2$TotalLoan), 
        type='bar') %>%
  layout(title = "All Years")
```

### By Month

```{r}
selectInput("yrs", label = "Select Year:",
            choices = c("2011","2012","2013", "2014"), selected = "2014")
dt2_1 <- reactive({
  accepted_loan_df %>% 
    filter(year == input$yrs) %>%
    group_by(month) %>% 
    summarise(TotalLoan = sum(as.numeric(loan_amnt), na.rm = T),
              NumberofLoans = n()) %>%
    as.data.frame()
})

output$by_month_plot <- renderPlotly({
  plot_ly(dt2_1(), 
          x=~month, 
          y=~TotalLoan, 
          text = dollar_format()(dt2_1()$TotalLoan), 
          color = ~month, 
          type='bar') %>%
    layout(title = paste(yr," - By Month",sep = ""))
}) 
plotlyOutput("by_month_plot")
```

EDA
=====================================

Row {data-width=500}
-----------------------------------------------------------------------
### Loan Status by Grade of Loan
```{r}
dt_2 <- accepted_loan_df %>%
  group_by(grade, loan_status) %>%
  summarise(Count = n())
dt_2$grade[1] <- NA
dt_2 <- dt_2[complete.cases(dt_2),]
plot_ly(dt_2, x = ~grade, y = ~Count, color = ~loan_status, type = 'bar') %>%
  layout(barmode = 'stack')
```

### Loan Status by Purpose of Loan
```{r}
dt_3 <- accepted_loan_df %>%
  group_by(purpose, loan_status) %>%
  summarise(Count = n())
dt_3$purpose[1] <- NA
dt_3 <- dt_3[complete.cases(dt_3),]
plot_ly(dt_3, x = ~purpose, y = ~Count, color = ~loan_status, type = 'bar') %>%
  layout(barmode = 'stack',
         margin = list(b = 100))
```

Row {data-width=500}
-----------------------------------------------------------------------
### Loan Status by Grade of Loan
```{r}
plot_ly(accepted_loan_df, x = ~loan_status, y = ~loan_amnt, color = ~loan_status, type = 'box') %>% layout(margin = list(b = 100))
```

### Loan Amount By Year
```{r}
dt_4 <- accepted_loan_df %>% 
  select(year, loan_amnt) %>% 
  na.omit(.) %>%
  group_by(year) %>%
  dplyr::summarize(Amount = sum(as.numeric(loan_amnt), na.rm = T), Volume = n(), AvgAmount = Amount/Volume)

ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "Volume"
)
plot_ly(dt_4, x = ~year) %>%
  add_lines(y = ~Amount, name = "Amount", type = 'scatter', mode = 'lines') %>%
  add_lines(y = ~Volume, name = "Volume", type = 'scatter', mode = 'lines', yaxis = 'y2') %>% 
  layout(yaxis2 = ay)
```

EDA-2
=====================================

Column {data-width=1000}
-----------------------------------------------------------------------

### Sub plots by grade and year
```{r}

# # Term, interest rate and grade: dataser preprocessing
# # Stacked boxplots
g_tig <- ggplot(accepted_loan_df, aes(grade, int_rate))
gt <- g_tig + geom_boxplot(outlier.size = 0.5, color = "red") + facet_grid(term ~
    year) + labs(title = "Interest Rate Distribution by Grade", x = "Grade",
    y = "Interest Rate(%)")
ggplotly(gt)

# lvls <- levels(factor(accepted_loan_df$year))
# lvls2 <- levels(factor(accepted_loan_df$term))
# plots_i <- list()
# plots_j <- list()
# for(i in seq_along(lvls)){
#   plots_i[[i]] <- accepted_loan_df %>% 
#       filter(year == lvls[i]) %>% 
#     plot_ly(.,x=~grade, y=~InterestRate, type="box")
# }
# 
# for(j in seq_along(lvls2)){
#   plots_j[[j]] <- dt %>%
#     filter(term == lvls2[j]) %>% 
#     plot_ly(.,x=~grade, y=~InterestRate, type="box")
# }
# subplot(plots_i,plots_j,nrows = 2)
```


Geographic Data
=====================================

Row {data-width=1000}
-----------------------------------------------------------------------

### US Map of Loan Data
```{r}
df <- accepted_loan_df %>% 
  select(loan_amnt, addr_state) %>%
  na.omit() %>% 
  group_by(addr_state) %>% 
  dplyr::summarise(TotalLoanAmount = sum(as.numeric(loan_amnt), na.rm = TRUE))

df$hover <- with(df, paste(addr_state, '<br>', "TotalLoanAmount", dollar_format()(TotalLoanAmount)))

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

plot_geo(df, locationmode = 'USA-states') %>%
  add_trace(
    z = ~TotalLoanAmount, text = ~hover, locations = ~addr_state,
    color = ~TotalLoanAmount, colors = 'Purples'
  ) %>%
  colorbar(title = "Millions USD") %>%
  layout(
    title = 'Lending Club Loans by State<br>(Hover for breakdown)',
    geo = g
  )
```

Row {data-width=1000}
-----------------------------------------------------------------------

### Heatmap of Why and how much people borrow

```{r}
heatmap_df <- accepted_loan_df %>%
  group_by(purpose) %>%
  summarise(Volume = n(),
            Avg_Amount = sum(as.numeric(loan_amnt), rm.na = TRUE)/n()) %>%
  arrange(-Volume, -Avg_Amount)

hchart(heatmap_df, "treemap", hcaes(x = purpose, value = Volume, color = Avg_Amount))

```

